const actionType = {
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  REGISTER: "REGISTER",

  LOGOUT: "LOGOUT",

  //User
  GET_CURRENT: "GET_CURRENT",
  GET_PRODUCT_BY_ID: "GET_PRODUCT_BY_ID",
  GET_PRODUCT_BY_OID: "GET_PRODUCT_BY_OID",
  GET_CATEGORY: "GET_CATEGORY",

  GET_PRODUCT: "GET_PRODUCT",
  UPDATE_QUANTITY: "UPDATE_QUANTITY",
};
export default actionType;
